agent:
  queue: public

steps:
  - name: lint-shellcheck
    plugins:
      - docker-compose#v5.4.1:
          run: lint-shellcheck

  - name: lint-plugin
    plugins:
      - docker-compose#v5.4.1:
          run: lint-plugin

  - name: bats tests
    plugins:
      - docker-compose#v5.4.1:
          run: tests
