#!/bin/bash

# vim: set ft=sh:

set -eou pipefail

declare brown="\033[33m"
declare green="\033[32m"
declare red="\033[31m"
declare reset="\033[0m"

main() {
  local addr="${BUILDKITE_PLUGIN_VAULT_GCP_CREDS_VAULT_ADDR:-}"
  local path="${BUILDKITE_PLUGIN_VAULT_GCP_CREDS_PATH:-gcp}"
  local account_name="${BUILDKITE_PLUGIN_VAULT_GCP_CREDS_ACCOUNT_NAME:-bk-$BUILDKITE_PIPELINE_SLUG}"
  local env_var="${BUILDKITE_PLUGIN_VAULT_GCP_CREDS_ENV_VAR:-CLOUDSDK_AUTH_ACCESS_TOKEN}"

  if [[ -z "$addr" ]]; then
    echo -e "~~~ :gcloud: ${brown}Vault GCP Creds Plugin${reset}. No 'vault_addr' specified. ${red}Skipping.${reset}"
    exit 0
  fi

  token=$(vault \
    read \
    -field=token \
    "${path}/impersonated-account/${account_name}/token"
  )
  export "${env_var}=$token"

  echo -e "~~~ :gcloud: ${brown}Vault GCP Creds Plugin${reset}: ${green}OK${reset}: CLOUDSDK_AUTH_ACCESS_TOKEN added to the environment."
}

main "$@"
